### ISSUE TITLE
Next step: a GUI?

### ISSUE THREAD

**Issue by FGRibreau** [marceloboeira/bojack#39]
Hello @marceloboeira :)

If you plan to make bojack production ready, you may want to also support [RESP](http://redis.io/topics/protocol) so you will get a full compatible GUI like [Redsmin](https://redsmin.com) that will offer bojack deployments free out-of-the-box real-time monitoring and alerting (on top of administrative tasks depending on your support of Redis commands) :)

For instance [tile38 will be doing this](https://github.com/tidwall/tile38/issues/37#issue-173262658) to get a free monitoring system from day one :)

**Comment by marceloboeira** [comment]
@FGRibreau I was thinking about RESP, but still not sure about it.

@hugoabonizio @mauricioabreu @cristianoliveira WDYT?

**Comment by hugoabonizio** [comment]
@FGRibreau @marceloboeira I think it's interesting, but that's the first time I read the specs of RESP. RESP seems to be simple and makes separations between types that can be good for us (since for now we only store string values and cast them when is necessary), and is an consolidated standard. I vote +1 to this, but for a future release.

**Comment by mauricioabreu** [comment]
it is a good feature, but I agree with @hugoabonizio : for a future release.
